openai_apikey = "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"
assistant_id = "asst_ErpNupkB9mW5AlM8jWJjMZWq"