openai_apikey = "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"
assistant_id = "asst_ErpNupkB9mW5AlM8jWJjMZWq"